name: Deploy Android Debug (BUILD)

on:
  workflow_dispatch:

jobs:
  distribute_dev_app_for_test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}'
    steps:
      - uses: actions/checkout@v3
      - name: Configure GIT
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
      - name: Add credentials
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS_BASE64 | base64 --decode > credentials.json
      - name: Save credentials into environment variables
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=./credentials.json" >> $GITHUB_ENV
      - name: Distribute dev app
        run: |
          bundle install
          bundle exec fastlane deployAndroidToFirebase