name: PR Checks

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"  # Skip static_check if commit message contains [ci skip]
    steps:
      - uses: actions/checkout@v3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Static Analysis
        run: |
          ./gradlew ktlint
          ./gradlew detekt
